#!/usr/bin/perl -w

# This script takes a root SRPMS directory as argument, and print the
# list of package names on stdout

use strict;
use URPM;

my $srpmsdir = $ARGV[0] or exit 1;

my $urpm = URPM->new;

foreach (glob("$srpmsdir/*/*/media_info/synthesis.hdlist.cz")) {
    $urpm->parse_synthesis($_);
}

my %res;
$urpm->traverse(sub { $res{$_[0]->name} = 1 });

print join("\n", sort(keys %res), '')
